name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/develop'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Deploy APP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          #password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script_stop: true
          command_timeout: 200m
          script: /
            cd /home/apps/api/git-actions-node
            git pull
            cd ..
            docker-compose build --force-rm --no-cache --compress
            docker-compose -f docker-compose.prod.yml up -d
